/* Generated by tools/make-sw.js — offline cache for Lockie Training */
const CACHE = 'baki-v2-f8fd0fc481';
const FILES = [
 "./",
 "./app.js",
 "./data.js",
 "./icons/apple-touch-icon.png",
 "./icons/icon-192.png",
 "./icons/icon-512.png",
 "./icons/icon-maskable-512.png",
 "./img/Barbell_Deadlift/0.jpg",
 "./img/Barbell_Incline_Bench_Press_-_Medium_Grip/0.jpg",
 "./img/Barbell_Shrug/0.jpg",
 "./img/Barbell_Squat/0.jpg",
 "./img/Bent_Over_Barbell_Row/0.jpg",
 "./img/Bodyweight_Walking_Lunge/0.jpg",
 "./img/Cable_Crunch/0.jpg",
 "./img/Cable_Hammer_Curls_-_Rope_Attachment/0.jpg",
 "./img/Cable_Rope_Overhead_Triceps_Extension/0.jpg",
 "./img/Cable_Seated_Lateral_Raise/0.jpg",
 "./img/Close-Grip_Barbell_Bench_Press/0.jpg",
 "./img/Dips_-_Chest_Version/0.jpg",
 "./img/Dumbbell_Bench_Press/0.jpg",
 "./img/Dumbbell_Incline_Row/0.jpg",
 "./img/Dumbbell_Shoulder_Press/0.jpg",
 "./img/Dumbbell_Shrug/0.jpg",
 "./img/EZ-Bar_Curl/0.jpg",
 "./img/EZ-Bar_Skullcrusher/0.jpg",
 "./img/Face_Pull/0.jpg",
 "./img/Farmers_Walk/0.jpg",
 "./img/Freehand_Jump_Squat/0.jpg",
 "./img/Front_Box_Jump/0.jpg",
 "./img/Hammer_Curls/0.jpg",
 "./img/Hanging_Leg_Raise/0.jpg",
 "./img/Incline_Dumbbell_Curl/0.jpg",
 "./img/Incline_Dumbbell_Press/0.jpg",
 "./img/LICENSE-free-exercise-db.md",
 "./img/Lateral_Bound/0.jpg",
 "./img/Leg_Press/0.jpg",
 "./img/Leverage_Iso_Row/0.jpg",
 "./img/Lying_Face_Down_Plate_Neck_Resistance/0.jpg",
 "./img/Lying_Face_Up_Plate_Neck_Resistance/0.jpg",
 "./img/Medicine_Ball_Chest_Pass/0.jpg",
 "./img/Medicine_Ball_Full_Twist/0.jpg",
 "./img/One-Arm_Kettlebell_Swings/0.jpg",
 "./img/One_Handed_Hang/0.jpg",
 "./img/Overhead_Slam/0.jpg",
 "./img/Plyo_Push-up/0.jpg",
 "./img/Pullups/0.jpg",
 "./img/Reverse_Barbell_Curl/0.jpg",
 "./img/Romanian_Deadlift/0.jpg",
 "./img/Seated_Bent-Over_Rear_Delt_Raise/0.jpg",
 "./img/Seated_Cable_Rows/0.jpg",
 "./img/Seated_Calf_Raise/0.jpg",
 "./img/Seated_Head_Harness_Neck_Resistance/0.jpg",
 "./img/Side_Lateral_Raise/0.jpg",
 "./img/Single-Leg_Lateral_Hop/0.jpg",
 "./img/Split_Squat_with_Dumbbells/0.jpg",
 "./img/Standing_Cable_Wood_Chop/0.jpg",
 "./img/Standing_Calf_Raises/0.jpg",
 "./img/Standing_Dumbbell_Triceps_Extension/0.jpg",
 "./img/Standing_Long_Jump/0.jpg",
 "./img/Standing_Military_Press/0.jpg",
 "./img/Stiff-Legged_Dumbbell_Deadlift/0.jpg",
 "./img/Trap_Bar_Deadlift/0.jpg",
 "./img/Triceps_Pushdown_-_Rope_Attachment/0.jpg",
 "./img/Wide-Grip_Lat_Pulldown/0.jpg",
 "./img/Wrist_Roller/0.jpg",
 "./index.html",
 "./manifest.webmanifest",
 "./styles.css"
];
self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILES)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  e.respondWith(caches.match(req, { ignoreSearch: true }).then(hit => hit || fetch(req).then(res => {
    if (res.ok) { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
    return res;
  }).catch(() => req.mode === 'navigate' ? caches.match('./index.html') : Response.error())));
});
